[package]
name = "Typify"
version = "1.0.0"
entrypoint = "app/template/main.typ"
authors = ["No√© Henchoz", "Yoan Gilliand"]
license = "MIT"
description = "A modular, ready-to-use template for modern Typst documents"
repository = "https://github.com/henchoznoe/Typify"